# Generated by Django 5.1.3 on 2024-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_address',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
